name: Gradle Dependency Submission
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Gradle Dependency Calculation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
    
      - name: 'Checkout Repository'
        uses: actions/checkout@v4 
        
      - name: 'Grant executable permissions to gradlew'
        run: chmod +x gradlew

      - name: 'Run dependency submission'
        uses: mikepenz/gradle-dependency-submission@v0.9.1
        with:
          gradle-project-path: .
          gradle-build-module: |
            :app
            :buildSrc
            :common:preferences
            :common:shared
            :common:theme
            :feature:anime:collection:data
            :feature:anime:collection:domain
            :feature:anime:collection:ui
            :feature:anime:core:common
            :feature:anime:core:data
            :feature:anime:core:domain
            :feature:anime:core:source:remote:api
            :feature:anime:core:source:remote:impl
            :feature:anime:detail:ui
            :feature:anime:exploration:domain
            :feature:anime:exploration:ui
            :feature:settings:data
            :feature:settings:domain
            :feature:settings:ui
          gradle-build-configuration: |-
            debugCompileClasspath
